# Use matches.csv to answer the below questions.

In [87]:
import pandas as pd
data1 = pd.read_csv(r'D:\Malathi\EDA\matches.csv')
data1.head()

,city,date,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,umpire1,Unnamed: 13
0,Bangalore,18-04-2008,BB McCullum,M Chinnaswamy Stadium,Royal Challengers Bangalore,Kolkata Knight Riders,Royal Challengers Bangalore,field,Kolkata Knight Riders,runs,140.0,N,Asad Rauf,Asad Rauf
1,Chandigarh,19-04-2008,MEK Hussey,"Punjab Cricket Association Stadium, Mohali",Kings XI Punjab,Chennai Super Kings,Chennai Super Kings,bat,Chennai Super Kings,runs,33.0,N,MR Benson,MR Benson
2,Delhi,19-04-2008,MF Maharoof,Feroz Shah Kotla,Delhi Daredevils,Rajasthan Royals,Rajasthan Royals,bat,Delhi Daredevils,wickets,9.0,N,Aleem Dar,Aleem Dar
3,Mumbai,20-04-2008,MV Boucher,Wankhede Stadium,Mumbai Indians,Royal Challengers Bangalore,Mumbai Indians,bat,Royal Challengers Bangalore,wickets,5.0,N,SJ Davis,SJ Davis
4,Kolkata,20-04-2008,DJ Hussey,Eden Gardens,Kolkata Knight Riders,Deccan Chargers,Deccan Chargers,bat,Kolkata Knight Riders,wickets,5.0,N,BF Bowden,BF Bowden

# 1. Total number of tosses won by CSK?

In [26]:
df1 = pd.pivot_table(data1, columns = 'team1', values = 'toss_winner', aggfunc = (lambda x:len(x)))
df1

team1,Chennai Super Kings,Deccan Chargers,Delhi Capitals,Delhi Daredevils,Gujarat Lions,Kings XI Punjab,Kochi Tuskers Kerala,Kolkata Knight Riders,Mumbai Indians,Pune Warriors,Rajasthan Royals,Rising Pune Supergiants,Rising Pune Supergiantss,Royal Challengers Bangalore,Sunrisers Hyderabad
toss_winner,94,39,19,83,16,92,7,95,97,23,70,7,7,108,59

In [27]:
df1['Chennai Super Kings']

toss_winner    94
Name: Chennai Super Kings, dtype: int64

# 2. How many eliminator matches were held in Abu Dhabi and Dubai?

In [33]:
df2 = pd.pivot_table(data1, columns = 'city', values = 'eliminator', 
               aggfunc = (lambda x:len(x)))
print(df2['Abu Dhabi'])
print(df2['Dubai'])

eliminator    29
Name: Abu Dhabi, dtype: int64
eliminator    26
Name: Dubai, dtype: int64

# 3. Who got the most Player of the match award after the year 2015 (2015 excluded)?

In [61]:
from datetime import date
data1['date'] = pd.to_datetime(data1['date'])
after_2015 = data1[data1['date'] > pd.Timestamp(date(2015,12,31))]
after_2015

,city,date,player_of_match,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,umpire1,Unnamed: 13
517,Mumbai,2016-09-04,AM Rahane,Wankhede Stadium,Mumbai Indians,Rising Pune Supergiantss,Mumbai Indians,bat,Rising Pune Supergiantss,wickets,9.0,N,HDPK Dharmasena,NaN
518,Kolkata,2016-10-04,AD Russell,Eden Gardens,Kolkata Knight Riders,Delhi Daredevils,Kolkata Knight Riders,field,Kolkata Knight Riders,wickets,9.0,N,S Ravi,NaN
519,Chandigarh,2016-11-04,AJ Finch,"Punjab Cricket Association IS Bindra Stadium, ...",Kings XI Punjab,Gujarat Lions,Gujarat Lions,field,Gujarat Lions,wickets,5.0,N,AK Chaudhary,NaN
520,Bangalore,2016-12-04,AB de Villiers,M Chinnaswamy Stadium,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Royal Challengers Bangalore,runs,45.0,N,HDPK Dharmasena,NaN
521,Kolkata,2016-04-13,RG Sharma,Eden Gardens,Kolkata Knight Riders,Mumbai Indians,Mumbai Indians,field,Mumbai Indians,wickets,6.0,N,Nitin Menon,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
811,Dubai,2020-09-28,AB de Villiers,Dubai International Cricket Stadium,Royal Challengers Bangalore,Mumbai Indians,Mumbai Indians,field,Royal Challengers Bangalore,tie,NaN,Y,Nitin Menon,NaN
812,Dubai,2020-05-11,JJ Bumrah,Dubai International Cricket Stadium,Mumbai Indians,Delhi Capitals,Delhi Capitals,field,Mumbai Indians,runs,57.0,N,CB Gaffaney,NaN
813,Abu Dhabi,2020-06-11,KS Williamson,Sheikh Zayed Stadium,Royal Challengers Bangalore,Sunrisers Hyderabad,Sunrisers Hyderabad,field,Sunrisers Hyderabad,wickets,6.0,N,PR Reiffel,NaN
814,Abu Dhabi,2020-08-11,MP Stoinis,Sheikh Zayed Stadium,Delhi Capitals,Sunrisers Hyderabad,Delhi Capitals,bat,Delhi Capitals,runs,17.0,N,PR Reiffel,NaN
815,Dubai,2020-10-11,TA Boult,Dubai International Cricket Stadium,Delhi Capitals,Mumbai Indians,Delhi Capitals,bat,Mumbai Indians,wickets,5.0,N,CB Gaffaney,NaN

In [74]:
obj = after_2015.groupby('player_of_match')
obj.first()

,city,date,venue,team1,team2,toss_winner,toss_decision,winner,result,result_margin,eliminator,umpire1,Unnamed: 13
player_of_match,,,,,,,,,,,,,
A Mishra,Delhi,2016-04-15,Feroz Shah Kotla,Delhi Daredevils,Kings XI Punjab,Delhi Daredevils,field,Delhi Daredevils,wickets,8.0,N,S Ravi,None
A Nehra,Visakhapatnam,2016-08-05,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Mumbai Indians,Sunrisers Hyderabad,Mumbai Indians,field,Sunrisers Hyderabad,runs,85.0,N,S Ravi,None
A Nortje,Abu Dhabi,2020-02-11,Sheikh Zayed Stadium,Royal Challengers Bangalore,Delhi Capitals,Delhi Capitals,field,Delhi Capitals,wickets,6.0,N,CB Gaffaney,None
A Zampa,Visakhapatnam,2016-10-05,Dr. Y.S. Rajasekhara Reddy ACA-VDCA Cricket St...,Rising Pune Supergiantss,Sunrisers Hyderabad,Sunrisers Hyderabad,bat,Sunrisers Hyderabad,runs,4.0,N,CB Gaffaney,None
AB Dinda,Hyderabad,2016-04-26,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,Rising Pune Supergiantss,Rising Pune Supergiantss,field,Rising Pune Supergiantss,runs,34.0,N,AY Dandekar,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
WP Saha,Mumbai,2017-11-05,Wankhede Stadium,Mumbai Indians,Kings XI Punjab,Mumbai Indians,field,Kings XI Punjab,runs,7.0,N,A Deshmukh,None
Washington Sundar,Mumbai,2017-05-16,Wankhede Stadium,Mumbai Indians,Rising Pune Supergiants,Mumbai Indians,field,Rising Pune Supergiants,runs,20.0,N,S Ravi,None
YK Pathan,Kolkata,2016-05-14,Eden Gardens,Kolkata Knight Riders,Rising Pune Supergiantss,Rising Pune Supergiantss,bat,Kolkata Knight Riders,wickets,8.0,N,A Nand Kishore,None
YS Chahal,Abu Dhabi,2020-03-10,Sheikh Zayed Stadium,Rajasthan Royals,Royal Challengers Bangalore,Rajasthan Royals,bat,Royal Challengers Bangalore,wickets,8.0,N,CB Gaffaney,None
Yuvraj Singh,Hyderabad,2017-05-04,"Rajiv Gandhi International Stadium, Uppal",Sunrisers Hyderabad,Royal Challengers Bangalore,Royal Challengers Bangalore,field,Sunrisers Hyderabad,runs,35.0,N,AY Dandekar,None

In [75]:
obj.size()[obj.size()==max(obj.size())]

player_of_match
AB de Villiers    12
dtype: int64

# 4. In how many matches Rohit Sharma (RG Sharma in the data) was awarded Player of the match after the year 2015?

In [76]:
obj.size()['RG Sharma']

9

# 5. How many unique umpires are present in the data?

In [77]:
umpires = data1.umpire1.unique()
len(umpires)

48

# 6. In how many matches the toss winner went on to win the match?

In [81]:
len(data1[data1['toss_winner']==data1['winner']])

418

# 7. After 2015, print a table listing down the number of matches won by batting first and fielding first like the one given below:

In [86]:
df4 = pd.pivot_table(data1, columns = 'winner', values = 'date', index = ['toss_decision'], 
               aggfunc = (lambda x:len(x)))
df4.T

toss_decision                 bat  field
winner
Chennai Super Kings          55.0   51.0
Deccan Chargers              14.0   15.0
Delhi Capitals                5.0   14.0
Delhi Daredevils             29.0   38.0
Gujarat Lions                 2.0   11.0
Kings XI Punjab              24.0   64.0
Kochi Tuskers Kerala          NaN    6.0
Kolkata Knight Riders        38.0   61.0
Mumbai Indians               50.0   70.0
Pune Warriors                 9.0    3.0
Rajasthan Royals             37.0   44.0
Rising Pune Supergiants       NaN   10.0
Rising Pune Supergiantss      2.0    3.0
Royal Challengers Bangalore  31.0   60.0
Sunrisers Hyderabad          23.0   43.0

 # 8. Total matches won by Mumbai Indians in the Wankhede Stadium?

In [88]:
len(data1[(data1['winner']=='Mumbai Indians') & (data1['venue']=='Wankhede Stadium')])

42

# 9. Use the student_1 and student_2 excel files to answer the below question:

In [92]:
import pandas as pd
data2 = pd.read_excel(r'D:\Malathi\EDA\student_1.xlsx')
data3 = pd.read_excel(r'D:\Malathi\EDA\student_2.xlsx')
data2.head()

,num,11 Jul 2022,12 Jul 2022,13 Jul 2022,14 Jul 2022,19 Jul 2022,21 Jul 2022,26 Jul 2022
0,21110077,P,P,P,P,P,P,P
1,21110219,P,P,P,A,P,P,P
2,21110278,P,P,P,P,P,P,P
3,21110467,P,P,P,P,P,P,P
4,21110451,P,P,P,P,P,P,A

In [93]:
data3.head()

   roll_number         Program  Registration Number
0     21110072  B.Tech AI & DS          21011101001
1     21110024  B.Tech AI & DS          21011101002
2     21110136  B.Tech AI & DS          21011101003
3     21110276  B.Tech AI & DS          21011101004
4     21110220  B.Tech AI & DS          21011101005

# 1. Get columns Registration number and Program in student_1 which should come from student_2

In [96]:
merged = pd.merge(data2, data3, left_on = 'num', right_on = 'roll_number')
merged

,num,11 Jul 2022,12 Jul 2022,13 Jul 2022,14 Jul 2022,19 Jul 2022,21 Jul 2022,26 Jul 2022,roll_number,Program,Registration Number
0,21110077,P,P,P,P,P,P,P,21110077,B.Tech CSE (IoT),21011102006
1,21110219,P,P,P,A,P,P,P,21110219,B.Tech CSE (IoT),21011102002
2,21110278,P,P,P,P,P,P,P,21110278,B.Tech CSE (IoT),21011102057
3,21110451,P,P,P,P,P,P,A,21110451,B.Tech CSE (IoT),21011102017
4,21110103,P,P,P,P,P,P,P,21110103,B.Tech CSE (IoT),21011102020
5,21110274,P,P,P,P,P,P,P,21110274,B.Tech CSE (IoT),21011102021
6,21110329,P,P,P,A,P,P,A,21110329,B.Tech CSE (IoT),21011102013
7,21110439,P,P,P,P,P,P,P,21110439,B.Tech CSE (IoT),21011102056
8,21110336,P,P,P,P,P,P,P,21110336,B.Tech CSE (IoT),21011102022
9,21110054,P,P,P,P,P,P,P,21110054,B.Tech CSE (IoT),21011102008
10,21110016,P,P,P,P,P,P,A,21110016,B.Tech CSE (IoT),21011102011
11,21110447,P,P,P,P,P,P,P,21110447,B.Tech CSE (IoT),21011102024
12,21110155,P,P,P,P,P,P,P,21110155,B.Tech CSE (IoT),21011102025
13,21110280,P,P,P,P,P,P,P,21110280,B.Tech CSE (IoT),21011102016
14,21110017,P,P,P,P,P,P,P,21110017,B.Tech CSE (IoT),21011102003
15,21110057,A,A,P,P,P,P,P,21110057,B.Tech CSE (IoT),21011102033
16,21110144,P,P,P,P,P,P,A,21110144,B.Tech CSE (IoT),21011102032
17,21110079,P,P,P,P,P,P,P,21110079,B.Tech CSE (IoT),21011102007
18,21110207,P,P,P,P,P,P,P,21110207,B.Tech CSE (IoT),21011102014
19,21110419,P,P,A,P,P,P,P,21110419,B.Tech CSE (IoT),21011102041
20,21110083,P,P,P,P,A,A,A,21110083,B.Tech CSE (IoT),21011102018
21,21110408,P,P,P,P,P,P,P,21110408,B.Tech CSE (IoT),21011102044
22,21110067,P,P,P,P,P,P,A,21110067,B.Tech CSE (IoT),21011102010
23,21110457,P,P,P,P,P,P,P,21110457,B.Tech CSE (IoT),21011102046
24,21110140,P,P,P,P,A,A,P,21110140,B.Tech CSE (IoT),21011102050
25,21110005,P,P,P,P,P,P,P,21110005,B.Tech CSE (IoT),21011102048
26,21110437,P,P,P,P,P,P,P,21110437,B.Tech CSE (IoT),21011102049
27,21110426,P,P,P,P,P,A,P,21110426,B.Tech CSE (IoT),21011102054
28,21110409,P,P,P,A,A,P,P,21110409,B.Tech CSE (IoT),21011102015
29,21110122,P,P,P,P,P,P,P,21110122,B.Tech CSE (IoT),21011102035
30,21110429,P,P,P,P,P,P,P,21110429,B.Tech CSE (IoT),21011102038
31,21110304,P,P,P,P,A,P,P,21110304,B.Tech CSE (IoT),21011102030
32,21110110,P,P,P,P,P,P,P,21110110,B.Tech CSE (IoT),21011102023
33,21110449,P,P,P,A,A,P,P,21110449,B.Tech CSE (IoT),21011102052
34,21110124,P,P,P,P,P,P,P,21110124,B.Tech CSE (IoT),21011102040
35,21110230,P,P,P,P,P,P,P,21110230,B.Tech CSE (IoT),21011102019
36,21110173,P,P,P,P,P,P,P,21110173,B.Tech CSE (IoT),21011102005
37,21110156,P,P,P,P,A,P,A,21110156,B.Tech CSE (IoT),21011102012
38,21110217,P,P,P,P,A,A,A,21110217,B.Tech CSE (IoT),21011102053
39,21110263,P,P,P,P,P,P,P,21110263,B.Tech CSE (IoT),21011102051
40,21110074,P,P,P,P,P,P,P,21110074,B.Tech CSE (IoT),21011102028
41,21110161,P,P,P,P,P,P,P,21110161,B.Tech CSE (IoT),21011102029
42,21110037,P,P,P,P,P,P,A,21110037,B.Tech CSE (IoT),21011102031
43,21110068,P,P,P,P,P,A,P,21110068,B.Tech CSE (IoT),21011102039
44,21110330,P,P,P,P,P,P,P,21110330,B.Tech CSE (IoT),21011102004
45,21110399,P,P,P,P,P,P,P,21110399,B.Tech CSE (IoT),21011102058
46,21110415,P,P,P,P,P,P,P,21110415,B.Tech CSE (IoT),21011102034
47,21110335,P,P,P,P,P,P,P,21110335,B.Tech CSE (IoT),21011102026
48,21110008,P,P,P,P,P,P,P,21110008,B.Tech CSE (IoT),21011102047
49,21110192,P,P,P,P,P,P,P,21110192,B.Tech CSE (IoT),21011102037
50,21110421,P,P,P,A,P,P,P,21110421,B.Tech CSE (IoT),21011102009
51,21110320,P,P,P,A,P,P,P,21110320,B.Tech CSE (IoT),21011102055
52,21110311,P,P,P,P,P,P,P,21110311,B.Tech CSE (IoT),21011102059
53,21110456,P,P,P,P,P,A,P,21110456,B.Tech CSE (IoT),21011102042
54,21110406,P,P,P,P,P,P,P,21110406,B.Tech CSE (IoT),21011102045
55,21110211,P,P,P,P,A,P,P,21110211,B.Tech CSE (IoT),21011102027
56,21110463,P,P,P,P,P,P,A,21110463,B.Tech CSE (IoT),21011102043

In [99]:
merged.drop('roll_number', axis = 1)

,num,11 Jul 2022,12 Jul 2022,13 Jul 2022,14 Jul 2022,19 Jul 2022,21 Jul 2022,26 Jul 2022,Program,Registration Number
0,21110077,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102006
1,21110219,P,P,P,A,P,P,P,B.Tech CSE (IoT),21011102002
2,21110278,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102057
3,21110451,P,P,P,P,P,P,A,B.Tech CSE (IoT),21011102017
4,21110103,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102020
5,21110274,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102021
6,21110329,P,P,P,A,P,P,A,B.Tech CSE (IoT),21011102013
7,21110439,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102056
8,21110336,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102022
9,21110054,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102008
10,21110016,P,P,P,P,P,P,A,B.Tech CSE (IoT),21011102011
11,21110447,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102024
12,21110155,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102025
13,21110280,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102016
14,21110017,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102003
15,21110057,A,A,P,P,P,P,P,B.Tech CSE (IoT),21011102033
16,21110144,P,P,P,P,P,P,A,B.Tech CSE (IoT),21011102032
17,21110079,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102007
18,21110207,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102014
19,21110419,P,P,A,P,P,P,P,B.Tech CSE (IoT),21011102041
20,21110083,P,P,P,P,A,A,A,B.Tech CSE (IoT),21011102018
21,21110408,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102044
22,21110067,P,P,P,P,P,P,A,B.Tech CSE (IoT),21011102010
23,21110457,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102046
24,21110140,P,P,P,P,A,A,P,B.Tech CSE (IoT),21011102050
25,21110005,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102048
26,21110437,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102049
27,21110426,P,P,P,P,P,A,P,B.Tech CSE (IoT),21011102054
28,21110409,P,P,P,A,A,P,P,B.Tech CSE (IoT),21011102015
29,21110122,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102035
30,21110429,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102038
31,21110304,P,P,P,P,A,P,P,B.Tech CSE (IoT),21011102030
32,21110110,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102023
33,21110449,P,P,P,A,A,P,P,B.Tech CSE (IoT),21011102052
34,21110124,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102040
35,21110230,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102019
36,21110173,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102005
37,21110156,P,P,P,P,A,P,A,B.Tech CSE (IoT),21011102012
38,21110217,P,P,P,P,A,A,A,B.Tech CSE (IoT),21011102053
39,21110263,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102051
40,21110074,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102028
41,21110161,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102029
42,21110037,P,P,P,P,P,P,A,B.Tech CSE (IoT),21011102031
43,21110068,P,P,P,P,P,A,P,B.Tech CSE (IoT),21011102039
44,21110330,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102004
45,21110399,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102058
46,21110415,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102034
47,21110335,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102026
48,21110008,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102047
49,21110192,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102037
50,21110421,P,P,P,A,P,P,P,B.Tech CSE (IoT),21011102009
51,21110320,P,P,P,A,P,P,P,B.Tech CSE (IoT),21011102055
52,21110311,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102059
53,21110456,P,P,P,P,P,A,P,B.Tech CSE (IoT),21011102042
54,21110406,P,P,P,P,P,P,P,B.Tech CSE (IoT),21011102045
55,21110211,P,P,P,P,A,P,P,B.Tech CSE (IoT),21011102027
56,21110463,P,P,P,P,P,P,A,B.Tech CSE (IoT),21011102043

# Create a column called attendance. The column should contain the number of hours each student is present

In [100]:
merged['attendance'] = 0

In [103]:
import numpy as np
merged.loc[:,'11 Jul 2022':'26 Jul 2022'] = np.where(merged.loc[:,'11 Jul 2022':'26 Jul 2022']=='P', 1, 0)

In [104]:
merged

,num,11 Jul 2022,12 Jul 2022,13 Jul 2022,14 Jul 2022,19 Jul 2022,21 Jul 2022,26 Jul 2022,roll_number,Program,Registration Number,attendance
0,21110077,1,1,1,1,1,1,1,21110077,B.Tech CSE (IoT),21011102006,0
1,21110219,1,1,1,0,1,1,1,21110219,B.Tech CSE (IoT),21011102002,0
2,21110278,1,1,1,1,1,1,1,21110278,B.Tech CSE (IoT),21011102057,0
3,21110451,1,1,1,1,1,1,0,21110451,B.Tech CSE (IoT),21011102017,0
4,21110103,1,1,1,1,1,1,1,21110103,B.Tech CSE (IoT),21011102020,0
5,21110274,1,1,1,1,1,1,1,21110274,B.Tech CSE (IoT),21011102021,0
6,21110329,1,1,1,0,1,1,0,21110329,B.Tech CSE (IoT),21011102013,0
7,21110439,1,1,1,1,1,1,1,21110439,B.Tech CSE (IoT),21011102056,0
8,21110336,1,1,1,1,1,1,1,21110336,B.Tech CSE (IoT),21011102022,0
9,21110054,1,1,1,1,1,1,1,21110054,B.Tech CSE (IoT),21011102008,0
10,21110016,1,1,1,1,1,1,0,21110016,B.Tech CSE (IoT),21011102011,0
11,21110447,1,1,1,1,1,1,1,21110447,B.Tech CSE (IoT),21011102024,0
12,21110155,1,1,1,1,1,1,1,21110155,B.Tech CSE (IoT),21011102025,0
13,21110280,1,1,1,1,1,1,1,21110280,B.Tech CSE (IoT),21011102016,0
14,21110017,1,1,1,1,1,1,1,21110017,B.Tech CSE (IoT),21011102003,0
15,21110057,0,0,1,1,1,1,1,21110057,B.Tech CSE (IoT),21011102033,0
16,21110144,1,1,1,1,1,1,0,21110144,B.Tech CSE (IoT),21011102032,0
17,21110079,1,1,1,1,1,1,1,21110079,B.Tech CSE (IoT),21011102007,0
18,21110207,1,1,1,1,1,1,1,21110207,B.Tech CSE (IoT),21011102014,0
19,21110419,1,1,0,1,1,1,1,21110419,B.Tech CSE (IoT),21011102041,0
20,21110083,1,1,1,1,0,0,0,21110083,B.Tech CSE (IoT),21011102018,0
21,21110408,1,1,1,1,1,1,1,21110408,B.Tech CSE (IoT),21011102044,0
22,21110067,1,1,1,1,1,1,0,21110067,B.Tech CSE (IoT),21011102010,0
23,21110457,1,1,1,1,1,1,1,21110457,B.Tech CSE (IoT),21011102046,0
24,21110140,1,1,1,1,0,0,1,21110140,B.Tech CSE (IoT),21011102050,0
25,21110005,1,1,1,1,1,1,1,21110005,B.Tech CSE (IoT),21011102048,0
26,21110437,1,1,1,1,1,1,1,21110437,B.Tech CSE (IoT),21011102049,0
27,21110426,1,1,1,1,1,0,1,21110426,B.Tech CSE (IoT),21011102054,0
28,21110409,1,1,1,0,0,1,1,21110409,B.Tech CSE (IoT),21011102015,0
29,21110122,1,1,1,1,1,1,1,21110122,B.Tech CSE (IoT),21011102035,0
30,21110429,1,1,1,1,1,1,1,21110429,B.Tech CSE (IoT),21011102038,0
31,21110304,1,1,1,1,0,1,1,21110304,B.Tech CSE (IoT),21011102030,0
32,21110110,1,1,1,1,1,1,1,21110110,B.Tech CSE (IoT),21011102023,0
33,21110449,1,1,1,0,0,1,1,21110449,B.Tech CSE (IoT),21011102052,0
34,21110124,1,1,1,1,1,1,1,21110124,B.Tech CSE (IoT),21011102040,0
35,21110230,1,1,1,1,1,1,1,21110230,B.Tech CSE (IoT),21011102019,0
36,21110173,1,1,1,1,1,1,1,21110173,B.Tech CSE (IoT),21011102005,0
37,21110156,1,1,1,1,0,1,0,21110156,B.Tech CSE (IoT),21011102012,0
38,21110217,1,1,1,1,0,0,0,21110217,B.Tech CSE (IoT),21011102053,0
39,21110263,1,1,1,1,1,1,1,21110263,B.Tech CSE (IoT),21011102051,0
40,21110074,1,1,1,1,1,1,1,21110074,B.Tech CSE (IoT),21011102028,0
41,21110161,1,1,1,1,1,1,1,21110161,B.Tech CSE (IoT),21011102029,0
42,21110037,1,1,1,1,1,1,0,21110037,B.Tech CSE (IoT),21011102031,0
43,21110068,1,1,1,1,1,0,1,21110068,B.Tech CSE (IoT),21011102039,0
44,21110330,1,1,1,1,1,1,1,21110330,B.Tech CSE (IoT),21011102004,0
45,21110399,1,1,1,1,1,1,1,21110399,B.Tech CSE (IoT),21011102058,0
46,21110415,1,1,1,1,1,1,1,21110415,B.Tech CSE (IoT),21011102034,0
47,21110335,1,1,1,1,1,1,1,21110335,B.Tech CSE (IoT),21011102026,0
48,21110008,1,1,1,1,1,1,1,21110008,B.Tech CSE (IoT),21011102047,0
49,21110192,1,1,1,1,1,1,1,21110192,B.Tech CSE (IoT),21011102037,0
50,21110421,1,1,1,0,1,1,1,21110421,B.Tech CSE (IoT),21011102009,0
51,21110320,1,1,1,0,1,1,1,21110320,B.Tech CSE (IoT),21011102055,0
52,21110311,1,1,1,1,1,1,1,21110311,B.Tech CSE (IoT),21011102059,0
53,21110456,1,1,1,1,1,0,1,21110456,B.Tech CSE (IoT),21011102042,0
54,21110406,1,1,1,1,1,1,1,21110406,B.Tech CSE (IoT),21011102045,0
55,21110211,1,1,1,1,0,1,1,21110211,B.Tech CSE (IoT),21011102027,0
56,21110463,1,1,1,1,1,1,0,21110463,B.Tech CSE (IoT),21011102043,0

In [105]:
merged['attendance'] = merged.loc[:,'11 Jul 2022':'26 Jul 2022'].T.sum(axis=0)

In [106]:
merged

,num,11 Jul 2022,12 Jul 2022,13 Jul 2022,14 Jul 2022,19 Jul 2022,21 Jul 2022,26 Jul 2022,roll_number,Program,Registration Number,attendance
0,21110077,1,1,1,1,1,1,1,21110077,B.Tech CSE (IoT),21011102006,7
1,21110219,1,1,1,0,1,1,1,21110219,B.Tech CSE (IoT),21011102002,6
2,21110278,1,1,1,1,1,1,1,21110278,B.Tech CSE (IoT),21011102057,7
3,21110451,1,1,1,1,1,1,0,21110451,B.Tech CSE (IoT),21011102017,6
4,21110103,1,1,1,1,1,1,1,21110103,B.Tech CSE (IoT),21011102020,7
5,21110274,1,1,1,1,1,1,1,21110274,B.Tech CSE (IoT),21011102021,7
6,21110329,1,1,1,0,1,1,0,21110329,B.Tech CSE (IoT),21011102013,5
7,21110439,1,1,1,1,1,1,1,21110439,B.Tech CSE (IoT),21011102056,7
8,21110336,1,1,1,1,1,1,1,21110336,B.Tech CSE (IoT),21011102022,7
9,21110054,1,1,1,1,1,1,1,21110054,B.Tech CSE (IoT),21011102008,7
10,21110016,1,1,1,1,1,1,0,21110016,B.Tech CSE (IoT),21011102011,6
11,21110447,1,1,1,1,1,1,1,21110447,B.Tech CSE (IoT),21011102024,7
12,21110155,1,1,1,1,1,1,1,21110155,B.Tech CSE (IoT),21011102025,7
13,21110280,1,1,1,1,1,1,1,21110280,B.Tech CSE (IoT),21011102016,7
14,21110017,1,1,1,1,1,1,1,21110017,B.Tech CSE (IoT),21011102003,7
15,21110057,0,0,1,1,1,1,1,21110057,B.Tech CSE (IoT),21011102033,5
16,21110144,1,1,1,1,1,1,0,21110144,B.Tech CSE (IoT),21011102032,6
17,21110079,1,1,1,1,1,1,1,21110079,B.Tech CSE (IoT),21011102007,7
18,21110207,1,1,1,1,1,1,1,21110207,B.Tech CSE (IoT),21011102014,7
19,21110419,1,1,0,1,1,1,1,21110419,B.Tech CSE (IoT),21011102041,6
20,21110083,1,1,1,1,0,0,0,21110083,B.Tech CSE (IoT),21011102018,4
21,21110408,1,1,1,1,1,1,1,21110408,B.Tech CSE (IoT),21011102044,7
22,21110067,1,1,1,1,1,1,0,21110067,B.Tech CSE (IoT),21011102010,6
23,21110457,1,1,1,1,1,1,1,21110457,B.Tech CSE (IoT),21011102046,7
24,21110140,1,1,1,1,0,0,1,21110140,B.Tech CSE (IoT),21011102050,5
25,21110005,1,1,1,1,1,1,1,21110005,B.Tech CSE (IoT),21011102048,7
26,21110437,1,1,1,1,1,1,1,21110437,B.Tech CSE (IoT),21011102049,7
27,21110426,1,1,1,1,1,0,1,21110426,B.Tech CSE (IoT),21011102054,6
28,21110409,1,1,1,0,0,1,1,21110409,B.Tech CSE (IoT),21011102015,5
29,21110122,1,1,1,1,1,1,1,21110122,B.Tech CSE (IoT),21011102035,7
30,21110429,1,1,1,1,1,1,1,21110429,B.Tech CSE (IoT),21011102038,7
31,21110304,1,1,1,1,0,1,1,21110304,B.Tech CSE (IoT),21011102030,6
32,21110110,1,1,1,1,1,1,1,21110110,B.Tech CSE (IoT),21011102023,7
33,21110449,1,1,1,0,0,1,1,21110449,B.Tech CSE (IoT),21011102052,5
34,21110124,1,1,1,1,1,1,1,21110124,B.Tech CSE (IoT),21011102040,7
35,21110230,1,1,1,1,1,1,1,21110230,B.Tech CSE (IoT),21011102019,7
36,21110173,1,1,1,1,1,1,1,21110173,B.Tech CSE (IoT),21011102005,7
37,21110156,1,1,1,1,0,1,0,21110156,B.Tech CSE (IoT),21011102012,5
38,21110217,1,1,1,1,0,0,0,21110217,B.Tech CSE (IoT),21011102053,4
39,21110263,1,1,1,1,1,1,1,21110263,B.Tech CSE (IoT),21011102051,7
40,21110074,1,1,1,1,1,1,1,21110074,B.Tech CSE (IoT),21011102028,7
41,21110161,1,1,1,1,1,1,1,21110161,B.Tech CSE (IoT),21011102029,7
42,21110037,1,1,1,1,1,1,0,21110037,B.Tech CSE (IoT),21011102031,6
43,21110068,1,1,1,1,1,0,1,21110068,B.Tech CSE (IoT),21011102039,6
44,21110330,1,1,1,1,1,1,1,21110330,B.Tech CSE (IoT),21011102004,7
45,21110399,1,1,1,1,1,1,1,21110399,B.Tech CSE (IoT),21011102058,7
46,21110415,1,1,1,1,1,1,1,21110415,B.Tech CSE (IoT),21011102034,7
47,21110335,1,1,1,1,1,1,1,21110335,B.Tech CSE (IoT),21011102026,7
48,21110008,1,1,1,1,1,1,1,21110008,B.Tech CSE (IoT),21011102047,7
49,21110192,1,1,1,1,1,1,1,21110192,B.Tech CSE (IoT),21011102037,7
50,21110421,1,1,1,0,1,1,1,21110421,B.Tech CSE (IoT),21011102009,6
51,21110320,1,1,1,0,1,1,1,21110320,B.Tech CSE (IoT),21011102055,6
52,21110311,1,1,1,1,1,1,1,21110311,B.Tech CSE (IoT),21011102059,7
53,21110456,1,1,1,1,1,0,1,21110456,B.Tech CSE (IoT),21011102042,6
54,21110406,1,1,1,1,1,1,1,21110406,B.Tech CSE (IoT),21011102045,7
55,21110211,1,1,1,1,0,1,1,21110211,B.Tech CSE (IoT),21011102027,6
56,21110463,1,1,1,1,1,1,0,21110463,B.Tech CSE (IoT),21011102043,6